# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2860d7fee8ba3329ed1d4cc9e7c394b7"
name = "gift-wrapper"
handle = "gift-wrapper-4"
application_url = "https://freeze-catherine-activity-payment.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "crush-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://freeze-catherine-activity-payment.trycloudflare.com/auth/callback",
  "https://freeze-catherine-activity-payment.trycloudflare.com/auth/shopify/callback",
  "https://freeze-catherine-activity-payment.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
